name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CodacyProjectToken }}
        run: ./gradlew build codacyCoverageReport -Porg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
